apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdotnet5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webappdotnet5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: webappdotnet5
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: webappdotnet5
        image: aspnet5webapp:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi
