name: .NET Core

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build_and_deploy:
    runs-on: ubuntu-20.04

    env:
      COMMIT_REF: $(git rev-parse --short "$GITHUB_SHA")

    steps:
      - uses: actions/checkout@v2

      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: Infrastructure/main.bicep

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: demoaspnet5aks-rg
          template: ./Infrastructure/main.json
          deploymentMode: Incremental

      - name: Build image with Azure Container Registry
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az acr build --registry ${{ steps.deploy.outputs.registryNameOutput }} --image aspnet5webapp:${{ env.COMMIT_REF }} ./WebApp/

      - name: Set Azure Kubernetes Service context
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}" # Azure credentials
          resource-group: ${{ steps.deploy.outputs.resourceGroupOutput }}
          cluster-name: ${{ steps.deploy.outputs.aksName }}
        id: login

      - uses: imranismail/setup-kustomize@v1

      - run: ./Kubernetes/kustomize edit set image aspnet5webapp:latest=${{ steps.deploy.outputs.registryNameOutput }}/aspnet5webapp:${{ env.COMMIT_REF }}}

      - run: ./Kubernetes/kustomize edit set image aspnet5webapp:latest=${{ steps.deploy.outputs.registryNameOutput }}/aspnet5webapp:${{ env.COMMIT_REF }}}

      - run: ./Kubernetes/kustomize build

      - name: Deploy to Azure Kubernetes Service
        uses: azure/k8s-deploy@v1.3
        with:
          namespace: "aspnet5webapp"
          manifests: |
            ./Kubernetes/namespace.yaml
            ./Kubernetes/deployment.yaml
            ./Kubernetes/service.yaml
          images: ${{ steps.deploy.outputs.registryNameOutput }}/aspnet5webapp:${{ env.COMMIT_REF }}}
          kubectl-version: "latest"
